// localization.js
// Centralized translations and t() utility

const translations = {
    en: {
        dashboard: 'Dashboard',
        settings: 'Settings',
        back: 'Back',
        theme: 'Theme',
        system: 'System',
        light: 'Light',
        dark: 'Dark',
        language: 'Language',
        currency: 'Currency',
        euro: 'Euro (€)',
        dollar: 'Dollar ($)',
        pound: 'Pound (£)',
        yen: 'Yen (¥)',
        franc: 'Swiss Franc (CHF)',
        name: 'Name',
        description: 'Description',
        customTags: 'Custom Tags',
        billingDetails: 'Billing Details',
        amount: 'Amount',
        billingPeriod: 'Billing Period',
        every: 'Every',
        month: 'Month',
        year: 'Year',
        firstPayment: 'First payment',
        billingMethod: 'Billing Method',
        colorAccent: 'Color Accent',
        saveChanges: 'Save Changes',
        createSubscription: 'Create Subscription',
        deleteSubscription: 'Delete Subscription',
        manageNotifications: 'Manage Notifications',
        notifications: 'Notifications',
        newNotification: 'New Notification',
        time: 'Time',
        message: 'Message',
        parametersInfo: 'Parameters will be replaced in the notification:',
        price: 'Price',
        timeUntil: 'Time until payment',
        subscriptionName: 'Subscription name',
        save: 'Save',
        cancel: 'Cancel',
        addFirst: 'Add your first',
        noSubscriptions: 'No subscriptions added yet.',
        searchPlaceholder: 'Search subscriptions...',
        upcomingBills: 'Upcoming Bills',
        totalMonthlySpend: 'Total Monthly Spend',
        acrossActive: 'Across {count} active subscriptions',
        noUpcoming: 'No bills coming up in the next month.',
        customMonths: 'Every {count} mos',
        // ...add more as needed
    },
    it: {
        dashboard: 'Cruscotto',
        settings: 'Impostazioni',
        back: 'Indietro',
        theme: 'Tema',
        system: 'Sistema',
        light: 'Chiaro',
        dark: 'Scuro',
        language: 'Lingua',
        currency: 'Valuta',
        euro: 'Euro (€)',
        dollar: 'Dollaro ($)',
        pound: 'Sterlina (£)',
        yen: 'Yen (¥)',
        franc: 'Franco Svizzero (CHF)',
        name: 'Nome',
        description: 'Descrizione',
        customTags: 'Tag personalizzati',
        billingDetails: 'Dati di fatturazione',
        amount: 'Importo',
        billingPeriod: 'Periodo di fatturazione',
        every: 'Ogni',
        month: 'Mese',
        year: 'Anno',
        firstPayment: 'Primo pagamento',
        billingMethod: 'Metodo di pagamento',
        colorAccent: 'Colore',
        saveChanges: 'Salva modifiche',
        createSubscription: 'Crea abbonamento',
        deleteSubscription: 'Elimina abbonamento',
        manageNotifications: 'Gestisci notifiche',
        notifications: 'Notifiche',
        newNotification: 'Nuova notifica',
        time: 'Ora',
        message: 'Messaggio',
        parametersInfo: 'I parametri saranno sostituiti nella notifica:',
        price: 'Prezzo',
        timeUntil: 'Tempo al pagamento',
        subscriptionName: 'Nome abbonamento',
        save: 'Salva',
        cancel: 'Annulla',
        addFirst: 'Aggiungi il primo',
        noSubscriptions: 'Nessun abbonamento aggiunto.',
        searchPlaceholder: 'Cerca abbonamenti...',
        upcomingBills: 'Prossime scadenze',
        totalMonthlySpend: 'Spesa mensile totale',
        acrossActive: 'Su {count} abbonamenti attivi',
        noUpcoming: 'Nessuna scadenza nel prossimo mese.',
        customMonths: 'Ogni {count} mesi',
        // ...add more as needed
    }
};

export function t(key, language = 'en', vars = {}) {
    let str = translations[language]?.[key] || translations['en'][key] || key;
    Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
    });
    return str;
}

export default translations;
